# Themes from: https://github.com/alacritty/alacritty-theme
import = ["~/dotfiles/alacritty/theme/gruvbox_material_hard_dark.toml"]

[font]
size = 11

[font.normal]
family = "Hack"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
